receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  # batch metrics before sending to reduce API usage
  batch:
    timeout: 5s
    send_batch_size: 512
    send_batch_max_size: 1024


exporters:
  logging:
    loglevel: debug

  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true


  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"


  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true
    const_labels:
      label1: value1

  otlphttp:
    endpoint: "https://otlp.nr-data.net:4318"
    tls:
      insecure: true
    headers:
      api-key: "8eea0c70ab4407a8df505abcebd74958FFFFNRAL"


# https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:


service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo,otlphttp]
    logs:
      receivers: [otlp]
      exporters: [loki]





